"""
ISO 3166-1 alpha-3 flag code → country name & emoji lookup.

Used by the enriched vessel endpoint to convert bare flag codes
(e.g. ``"PAN"``) into the rich object the frontend expects::

    {"code": "PAN", "name": "Panama", "emoji": "🇵🇦"}
"""

# Mapping of ISO 3166-1 alpha-3 codes used in maritime registries.
# Covers all major flag states and flags of convenience.
_FLAGS: dict[str, dict[str, str]] = {
    "AFG": {"name": "Afghanistan", "emoji": "🇦🇫"},
    "ALB": {"name": "Albania", "emoji": "🇦🇱"},
    "DZA": {"name": "Algeria", "emoji": "🇩🇿"},
    "AGO": {"name": "Angola", "emoji": "🇦🇴"},
    "ATG": {"name": "Antigua and Barbuda", "emoji": "🇦🇬"},
    "ARG": {"name": "Argentina", "emoji": "🇦🇷"},
    "AUS": {"name": "Australia", "emoji": "🇦🇺"},
    "AUT": {"name": "Austria", "emoji": "🇦🇹"},
    "AZE": {"name": "Azerbaijan", "emoji": "🇦🇿"},
    "BHS": {"name": "Bahamas", "emoji": "🇧🇸"},
    "BHR": {"name": "Bahrain", "emoji": "🇧🇭"},
    "BGD": {"name": "Bangladesh", "emoji": "🇧🇩"},
    "BRB": {"name": "Barbados", "emoji": "🇧🇧"},
    "BEL": {"name": "Belgium", "emoji": "🇧🇪"},
    "BLZ": {"name": "Belize", "emoji": "🇧🇿"},
    "BEN": {"name": "Benin", "emoji": "🇧🇯"},
    "BMU": {"name": "Bermuda", "emoji": "🇧🇲"},
    "BOL": {"name": "Bolivia", "emoji": "🇧🇴"},
    "BRA": {"name": "Brazil", "emoji": "🇧🇷"},
    "BRN": {"name": "Brunei", "emoji": "🇧🇳"},
    "BGR": {"name": "Bulgaria", "emoji": "🇧🇬"},
    "KHM": {"name": "Cambodia", "emoji": "🇰🇭"},
    "CMR": {"name": "Cameroon", "emoji": "🇨🇲"},
    "CAN": {"name": "Canada", "emoji": "🇨🇦"},
    "CPV": {"name": "Cabo Verde", "emoji": "🇨🇻"},
    "CYM": {"name": "Cayman Islands", "emoji": "🇰🇾"},
    "CHL": {"name": "Chile", "emoji": "🇨🇱"},
    "CHN": {"name": "China", "emoji": "🇨🇳"},
    "COL": {"name": "Colombia", "emoji": "🇨🇴"},
    "COM": {"name": "Comoros", "emoji": "🇰🇲"},
    "COG": {"name": "Congo", "emoji": "🇨🇬"},
    "COK": {"name": "Cook Islands", "emoji": "🇨🇰"},
    "CRI": {"name": "Costa Rica", "emoji": "🇨🇷"},
    "HRV": {"name": "Croatia", "emoji": "🇭🇷"},
    "CUB": {"name": "Cuba", "emoji": "🇨🇺"},
    "CUW": {"name": "Curaçao", "emoji": "🇨🇼"},
    "CYP": {"name": "Cyprus", "emoji": "🇨🇾"},
    "CZE": {"name": "Czech Republic", "emoji": "🇨🇿"},
    "DNK": {"name": "Denmark", "emoji": "🇩🇰"},
    "DJI": {"name": "Djibouti", "emoji": "🇩🇯"},
    "DMA": {"name": "Dominica", "emoji": "🇩🇲"},
    "DOM": {"name": "Dominican Republic", "emoji": "🇩🇴"},
    "ECU": {"name": "Ecuador", "emoji": "🇪🇨"},
    "EGY": {"name": "Egypt", "emoji": "🇪🇬"},
    "GNQ": {"name": "Equatorial Guinea", "emoji": "🇬🇶"},
    "ERI": {"name": "Eritrea", "emoji": "🇪🇷"},
    "EST": {"name": "Estonia", "emoji": "🇪🇪"},
    "ETH": {"name": "Ethiopia", "emoji": "🇪🇹"},
    "FRO": {"name": "Faroe Islands", "emoji": "🇫🇴"},
    "FJI": {"name": "Fiji", "emoji": "🇫🇯"},
    "FIN": {"name": "Finland", "emoji": "🇫🇮"},
    "FRA": {"name": "France", "emoji": "🇫🇷"},
    "GAB": {"name": "Gabon", "emoji": "🇬🇦"},
    "GMB": {"name": "Gambia", "emoji": "🇬🇲"},
    "GEO": {"name": "Georgia", "emoji": "🇬🇪"},
    "DEU": {"name": "Germany", "emoji": "🇩🇪"},
    "GHA": {"name": "Ghana", "emoji": "🇬🇭"},
    "GIB": {"name": "Gibraltar", "emoji": "🇬🇮"},
    "GRC": {"name": "Greece", "emoji": "🇬🇷"},
    "GRD": {"name": "Grenada", "emoji": "🇬🇩"},
    "GTM": {"name": "Guatemala", "emoji": "🇬🇹"},
    "GIN": {"name": "Guinea", "emoji": "🇬🇳"},
    "GUY": {"name": "Guyana", "emoji": "🇬🇾"},
    "HTI": {"name": "Haiti", "emoji": "🇭🇹"},
    "HND": {"name": "Honduras", "emoji": "🇭🇳"},
    "HKG": {"name": "Hong Kong", "emoji": "🇭🇰"},
    "HUN": {"name": "Hungary", "emoji": "🇭🇺"},
    "ISL": {"name": "Iceland", "emoji": "🇮🇸"},
    "IND": {"name": "India", "emoji": "🇮🇳"},
    "IDN": {"name": "Indonesia", "emoji": "🇮🇩"},
    "IRN": {"name": "Iran", "emoji": "🇮🇷"},
    "IRQ": {"name": "Iraq", "emoji": "🇮🇶"},
    "IRL": {"name": "Ireland", "emoji": "🇮🇪"},
    "IMN": {"name": "Isle of Man", "emoji": "🇮🇲"},
    "ISR": {"name": "Israel", "emoji": "🇮🇱"},
    "ITA": {"name": "Italy", "emoji": "🇮🇹"},
    "JAM": {"name": "Jamaica", "emoji": "🇯🇲"},
    "JPN": {"name": "Japan", "emoji": "🇯🇵"},
    "JOR": {"name": "Jordan", "emoji": "🇯🇴"},
    "KAZ": {"name": "Kazakhstan", "emoji": "🇰🇿"},
    "KEN": {"name": "Kenya", "emoji": "🇰🇪"},
    "KIR": {"name": "Kiribati", "emoji": "🇰🇮"},
    "PRK": {"name": "North Korea", "emoji": "🇰🇵"},
    "KOR": {"name": "South Korea", "emoji": "🇰🇷"},
    "KWT": {"name": "Kuwait", "emoji": "🇰🇼"},
    "LVA": {"name": "Latvia", "emoji": "🇱🇻"},
    "LBN": {"name": "Lebanon", "emoji": "🇱🇧"},
    "LBR": {"name": "Liberia", "emoji": "🇱🇷"},
    "LBY": {"name": "Libya", "emoji": "🇱🇾"},
    "LTU": {"name": "Lithuania", "emoji": "🇱🇹"},
    "LUX": {"name": "Luxembourg", "emoji": "🇱🇺"},
    "MDG": {"name": "Madagascar", "emoji": "🇲🇬"},
    "MYS": {"name": "Malaysia", "emoji": "🇲🇾"},
    "MDV": {"name": "Maldives", "emoji": "🇲🇻"},
    "MLT": {"name": "Malta", "emoji": "🇲🇹"},
    "MHL": {"name": "Marshall Islands", "emoji": "🇲🇭"},
    "MRT": {"name": "Mauritania", "emoji": "🇲🇷"},
    "MUS": {"name": "Mauritius", "emoji": "🇲🇺"},
    "MEX": {"name": "Mexico", "emoji": "🇲🇽"},
    "FSM": {"name": "Micronesia", "emoji": "🇫🇲"},
    "MDA": {"name": "Moldova", "emoji": "🇲🇩"},
    "MCO": {"name": "Monaco", "emoji": "🇲🇨"},
    "MNG": {"name": "Mongolia", "emoji": "🇲🇳"},
    "MNE": {"name": "Montenegro", "emoji": "🇲🇪"},
    "MAR": {"name": "Morocco", "emoji": "🇲🇦"},
    "MOZ": {"name": "Mozambique", "emoji": "🇲🇿"},
    "MMR": {"name": "Myanmar", "emoji": "🇲🇲"},
    "NAM": {"name": "Namibia", "emoji": "🇳🇦"},
    "NRU": {"name": "Nauru", "emoji": "🇳🇷"},
    "NLD": {"name": "Netherlands", "emoji": "🇳🇱"},
    "NZL": {"name": "New Zealand", "emoji": "🇳🇿"},
    "NIC": {"name": "Nicaragua", "emoji": "🇳🇮"},
    "NER": {"name": "Niger", "emoji": "🇳🇪"},
    "NGA": {"name": "Nigeria", "emoji": "🇳🇬"},
    "NIU": {"name": "Niue", "emoji": "🇳🇺"},
    "NOR": {"name": "Norway", "emoji": "🇳🇴"},
    "OMN": {"name": "Oman", "emoji": "🇴🇲"},
    "PAK": {"name": "Pakistan", "emoji": "🇵🇰"},
    "PLW": {"name": "Palau", "emoji": "🇵🇼"},
    "PAN": {"name": "Panama", "emoji": "🇵🇦"},
    "PNG": {"name": "Papua New Guinea", "emoji": "🇵🇬"},
    "PRY": {"name": "Paraguay", "emoji": "🇵🇾"},
    "PER": {"name": "Peru", "emoji": "🇵🇪"},
    "PHL": {"name": "Philippines", "emoji": "🇵🇭"},
    "POL": {"name": "Poland", "emoji": "🇵🇱"},
    "PRT": {"name": "Portugal", "emoji": "🇵🇹"},
    "QAT": {"name": "Qatar", "emoji": "🇶🇦"},
    "ROU": {"name": "Romania", "emoji": "🇷🇴"},
    "RUS": {"name": "Russia", "emoji": "🇷🇺"},
    "KNA": {"name": "Saint Kitts and Nevis", "emoji": "🇰🇳"},
    "LCA": {"name": "Saint Lucia", "emoji": "🇱🇨"},
    "VCT": {"name": "Saint Vincent and the Grenadines", "emoji": "🇻🇨"},
    "WSM": {"name": "Samoa", "emoji": "🇼🇸"},
    "SAU": {"name": "Saudi Arabia", "emoji": "🇸🇦"},
    "SEN": {"name": "Senegal", "emoji": "🇸🇳"},
    "SRB": {"name": "Serbia", "emoji": "🇷🇸"},
    "SYC": {"name": "Seychelles", "emoji": "🇸🇨"},
    "SLE": {"name": "Sierra Leone", "emoji": "🇸🇱"},
    "SGP": {"name": "Singapore", "emoji": "🇸🇬"},
    "SVK": {"name": "Slovakia", "emoji": "🇸🇰"},
    "SVN": {"name": "Slovenia", "emoji": "🇸🇮"},
    "SLB": {"name": "Solomon Islands", "emoji": "🇸🇧"},
    "SOM": {"name": "Somalia", "emoji": "🇸🇴"},
    "ZAF": {"name": "South Africa", "emoji": "🇿🇦"},
    "ESP": {"name": "Spain", "emoji": "🇪🇸"},
    "LKA": {"name": "Sri Lanka", "emoji": "🇱🇰"},
    "SDN": {"name": "Sudan", "emoji": "🇸🇩"},
    "SUR": {"name": "Suriname", "emoji": "🇸🇷"},
    "SWE": {"name": "Sweden", "emoji": "🇸🇪"},
    "CHE": {"name": "Switzerland", "emoji": "🇨🇭"},
    "SYR": {"name": "Syria", "emoji": "🇸🇾"},
    "TWN": {"name": "Taiwan", "emoji": "🇹🇼"},
    "TZA": {"name": "Tanzania", "emoji": "🇹🇿"},
    "THA": {"name": "Thailand", "emoji": "🇹🇭"},
    "TGO": {"name": "Togo", "emoji": "🇹🇬"},
    "TON": {"name": "Tonga", "emoji": "🇹🇴"},
    "TTO": {"name": "Trinidad and Tobago", "emoji": "🇹🇹"},
    "TUN": {"name": "Tunisia", "emoji": "🇹🇳"},
    "TUR": {"name": "Turkey", "emoji": "🇹🇷"},
    "TKM": {"name": "Turkmenistan", "emoji": "🇹🇲"},
    "TUV": {"name": "Tuvalu", "emoji": "🇹🇻"},
    "UGA": {"name": "Uganda", "emoji": "🇺🇬"},
    "UKR": {"name": "Ukraine", "emoji": "🇺🇦"},
    "ARE": {"name": "United Arab Emirates", "emoji": "🇦🇪"},
    "GBR": {"name": "United Kingdom", "emoji": "🇬🇧"},
    "USA": {"name": "United States", "emoji": "🇺🇸"},
    "URY": {"name": "Uruguay", "emoji": "🇺🇾"},
    "VUT": {"name": "Vanuatu", "emoji": "🇻🇺"},
    "VEN": {"name": "Venezuela", "emoji": "🇻🇪"},
    "VNM": {"name": "Vietnam", "emoji": "🇻🇳"},
    "VGB": {"name": "British Virgin Islands", "emoji": "🇻🇬"},
    "AIA": {"name": "Anguilla", "emoji": "🇦🇮"},
    "MSR": {"name": "Montserrat", "emoji": "🇲🇸"},
    "TCA": {"name": "Turks and Caicos Islands", "emoji": "🇹🇨"},
    "FLK": {"name": "Falkland Islands", "emoji": "🇫🇰"},
    "SHN": {"name": "Saint Helena", "emoji": "🇸🇭"},
    "WLF": {"name": "Wallis and Futuna", "emoji": "🇼🇫"},
    "PYF": {"name": "French Polynesia", "emoji": "🇵🇫"},
    "NCL": {"name": "New Caledonia", "emoji": "🇳🇨"},
    "SPM": {"name": "Saint Pierre and Miquelon", "emoji": "🇵🇲"},
    "BLM": {"name": "Saint Barthélemy", "emoji": "🇧🇱"},
    "MAF": {"name": "Saint Martin", "emoji": "🇲🇫"},
    "SXM": {"name": "Sint Maarten", "emoji": "🇸🇽"},
    "ABW": {"name": "Aruba", "emoji": "🇦🇼"},
    "BES": {"name": "Bonaire", "emoji": "🇧🇶"},
    "GRL": {"name": "Greenland", "emoji": "🇬🇱"},
    "JEY": {"name": "Jersey", "emoji": "🇯🇪"},
    "GGY": {"name": "Guernsey", "emoji": "🇬🇬"},
    "LIE": {"name": "Liechtenstein", "emoji": "🇱🇮"},
    "SMR": {"name": "San Marino", "emoji": "🇸🇲"},
    "YEM": {"name": "Yemen", "emoji": "🇾🇪"},
    "ZMB": {"name": "Zambia", "emoji": "🇿🇲"},
    "ZWE": {"name": "Zimbabwe", "emoji": "🇿🇼"},
}

# Mapping of ITU Maritime Identification Digits (MID) to ISO alpha-3 flag codes
_MID_TO_ISO: dict[str, str] = {
    "209": "CYP", "210": "CYP", "212": "CYP",
    "211": "DEU",
    "224": "ESP", "225": "ESP",
    "226": "FRA", "227": "FRA", "228": "FRA",
    "232": "GBR", "233": "GBR", "234": "GBR", "235": "GBR",
    "240": "GRC", "241": "GRC",
    "247": "ITA",
    "248": "MLT", "249": "MLT", "256": "MLT",
    "273": "RUS",
    "304": "ATG", "305": "ATG",
    "310": "BMU",
    "311": "BHS",
    "312": "BLZ",
    "316": "CAN",
    "345": "CYM",
    "351": "PAN", "352": "PAN", "353": "PAN", "354": "PAN", "355": "PAN", "356": "PAN", "357": "PAN",
    "366": "USA", "367": "USA", "368": "USA", "369": "USA",
    "375": "VCT", "376": "VCT", "377": "VCT",
    "412": "CHN", "413": "CHN", "414": "CHN",
    "419": "IND",
    "431": "JPN", "432": "JPN",
    "440": "KOR", "441": "KOR",
    "477": "HKG",
    "503": "AUS",
    "525": "IDN",
    "533": "MYS",
    "538": "MHL",
    "563": "SGP", "564": "SGP", "565": "SGP", "566": "SGP",
    "574": "VNM",
    "576": "VUT", "577": "VUT",
    "601": "ZAF",
    "613": "CMR",
    "620": "COM",
    "636": "LBR",
    "657": "NGA",
    "671": "TGO",
    "710": "BRA",
}


def get_flag_info(code: str | None) -> dict[str, str] | None:
    """Return ``{"code": ..., "name": ..., "emoji": ...}`` for a flag code.

    Returns ``None`` if the code is not recognised.
    """
    if not code:
        return None
    entry = _FLAGS.get(code.upper())
    if entry is None:
        # Return a generic entry with the code only
        return {"code": code.upper(), "name": code.upper(), "emoji": "🏴"}
    return {"code": code.upper(), "name": entry["name"], "emoji": entry["emoji"]}


def get_flag_from_mmsi(mmsi: int | str | None) -> dict[str, str] | None:
    """Resolve flag state information from an MMSI using ITU MID prefixes.

    Args:
        mmsi: The 9-digit MMSI number as integer or string.

    Returns:
        Dict with keys code, name, emoji or None if unresolvable.
    """
    if mmsi is None:
        return None
    digits = str(mmsi).strip()
    if len(digits) < 3:
        return None
    mid = digits[:3]
    iso_code = _MID_TO_ISO.get(mid)
    if iso_code:
        return get_flag_info(iso_code)
    return {"code": "UNK", "name": "Unknown", "emoji": "🏳️"}
